// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCST24oa3TOUdv1UzAFcNUkAxSQDx-SsGo',
    appId: '1:1024502274026:web:db651728205c91a0df8493',
    messagingSenderId: '1024502274026',
    projectId: 'strings-205cd',
    authDomain: 'strings-205cd.firebaseapp.com',
    storageBucket: 'strings-205cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBvojXcViKs6wWrUXiG0JRQmpB1lY3F4',
    appId: '1:1024502274026:android:e7547b92dfbc44b4df8493',
    messagingSenderId: '1024502274026',
    projectId: 'strings-205cd',
    storageBucket: 'strings-205cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpF7wZ1A7CHFh-wy1YF2M5bnqiv5HXNY',
    appId: '1:1024502274026:ios:6dcf0368db7106a7df8493',
    messagingSenderId: '1024502274026',
    projectId: 'strings-205cd',
    storageBucket: 'strings-205cd.appspot.com',
    iosBundleId: 'com.indus.strings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpF7wZ1A7CHFh-wy1YF2M5bnqiv5HXNY',
    appId: '1:1024502274026:ios:6dcf0368db7106a7df8493',
    messagingSenderId: '1024502274026',
    projectId: 'strings-205cd',
    storageBucket: 'strings-205cd.appspot.com',
    iosBundleId: 'com.indus.strings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCST24oa3TOUdv1UzAFcNUkAxSQDx-SsGo',
    appId: '1:1024502274026:web:877b71333bd8b231df8493',
    messagingSenderId: '1024502274026',
    projectId: 'strings-205cd',
    authDomain: 'strings-205cd.firebaseapp.com',
    storageBucket: 'strings-205cd.appspot.com',
  );
}
